"""
AWS EC2 Provisioning — Native Python Task (with CMP Agent)

Provisions an AWS EC2 instance using boto3 with temporary credentials
from the CMP credential context. The original access keys are never
visible to this task.

After provisioning, the CMP monitoring agent is automatically installed
via user_data. The agent collects CPU, memory, disk, and network metrics
and reports them to the System Metrics tab on the resource detail page.

CMP injects context as:
    cmp["credential"]["aws_access_key_id"]      — temp or original key
    cmp["credential"]["aws_secret_access_key"]  — temp or original secret
    cmp["credential"]["aws_session_token"]      — STS session token (if assumed role)
    cmp["agent"]["token"]                       — one-time agent registration token
    cmp["agent"]["endpoint"]                    — CMP agent API endpoint
    cmp["agent"]["install_url"]                 — agent install script URL
    cmp["user_data"]                            — pre-built cloud-init script (SSH keys + agent install)
    params["instance_name"]                     — form data / step inputs
"""
import json
import sys
import time

try:
    import boto3
    from botocore.exceptions import ClientError
except ImportError:
    print("ERROR: boto3 is required. Install: pip install boto3")
    sys.exit(1)


def build_user_data(resource_id: str) -> str:
    """Build the EC2 user_data script that installs the CMP monitoring agent.
    
    Note: resource_id should be the EC2 instance ID (e.g. i-0abc123).
    Since we don't have it before launch, we pass a placeholder and
    the agent uses EC2 instance metadata to resolve it at runtime.
    """
    agent = cmp.get("agent", {})
    tenant_id = cmp.get("execution", {}).get("tenant_id", "default")

    if not agent.get("token"):
        # No agent context available — return empty user_data
        return ""

    script = f"""#!/bin/bash
# ============================================================
# CMP Agent Installation (auto-generated by provisioning task)
# ============================================================
# Wait for network and metadata to be available
sleep 10

# Resolve the actual instance ID from EC2 metadata
TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 60")
INSTANCE_ID=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-id)

# If metadata lookup fails, use the provisioned resource_id
if [ -z "$INSTANCE_ID" ]; then
    INSTANCE_ID="{resource_id}"
fi

# Install CMP monitoring agent (as root via user_data)
curl -sSL {agent['install_url']} | bash -s -- \\
  --endpoint {agent['endpoint']} \\
  --token {agent['token']} \\
  --resource-id $INSTANCE_ID \\
  --tenant-id {tenant_id}
"""
    return script


def main():
    credential = cmp.get("credential", {})
    aws_access_key = credential.get("aws_access_key_id", "")
    aws_secret_key = credential.get("aws_secret_access_key", "")
    aws_session_token = credential.get("aws_session_token", "")

    # Read inputs from params
    region = params.get("region", "us-east-1")
    instance_name = params.get("instance_name", "")
    instance_type = params.get("instance_type", "t3.micro")
    ami_id = params.get("ami_id", "")
    subnet_id = params.get("subnet_id", "")
    key_name = params.get("key_name", "")
    root_volume_size = int(params.get("root_volume_size_gb", "20"))
    root_volume_type = params.get("root_volume_type", "gp3")
    assign_public_ip = str(params.get("assign_public_ip", "true")).lower() in ("true", "1", "yes")
    install_agent = str(params.get("install_agent", "true")).lower() in ("true", "1", "yes")

    if not aws_access_key or not aws_secret_key:
        print("ERROR: No AWS credentials in credential context.")
        print(f"  Available credential keys: {list(credential.keys())}")
        sys.exit(1)

    if not instance_name:
        print("ERROR: instance_name is required.")
        sys.exit(1)

    if not ami_id:
        print("ERROR: ami_id is required.")
        sys.exit(1)

    print(f"[AWS] Provisioning EC2 instance '{instance_name}' in {region}")
    print(f"[AWS] Type: {instance_type}, AMI: {ami_id}, Volume: {root_volume_size}GB {root_volume_type}")
    print(f"[AWS] CMP Agent: {'will be installed' if install_agent else 'skipped'}")

    # Create boto3 session with temp credentials
    session_kwargs = {
        "aws_access_key_id": aws_access_key,
        "aws_secret_access_key": aws_secret_key,
        "region_name": region,
    }
    if aws_session_token:
        session_kwargs["aws_session_token"] = aws_session_token

    session = boto3.Session(**session_kwargs)
    ec2 = session.resource("ec2")
    ec2_client = session.client("ec2")

    # Build user_data with CMP agent installation
    # Option 1 (preferred): Use the pre-built user_data from CMP context
    #   This combines SSH keys + agent install into a single cloud-init script.
    # Option 2 (custom): Build manually from cmp["agent"] for fine-grained control.
    user_data = ""
    if install_agent:
        # Try pre-built user_data first (includes SSH keys + agent install)
        user_data = cmp.get("user_data", "")
        if not user_data:
            # Fallback: build manually from agent context
            user_data = build_user_data(instance_name)
        if user_data:
            print("[AWS] User data includes CMP Agent installation script")

    # Build instance parameters
    run_kwargs = {
        "ImageId": ami_id,
        "InstanceType": instance_type,
        "MinCount": 1,
        "MaxCount": 1,
        "BlockDeviceMappings": [
            {
                "DeviceName": "/dev/xvda",
                "Ebs": {
                    "VolumeSize": root_volume_size,
                    "VolumeType": root_volume_type,
                    "Encrypted": True,
                    "DeleteOnTermination": True,
                },
            }
        ],
        "TagSpecifications": [
            {
                "ResourceType": "instance",
                "Tags": [
                    {"Key": "Name", "Value": instance_name},
                    {"Key": "ManagedBy", "Value": "cmp"},
                    {"Key": "ProvisionedVia", "Value": "native-task"},
                    {"Key": "CMPAgent", "Value": "true" if install_agent else "false"},
                ],
            }
        ],
        "MetadataOptions": {
            "HttpTokens": "required",
            "HttpEndpoint": "enabled",
        },
    }

    if user_data:
        run_kwargs["UserData"] = user_data

    if subnet_id:
        run_kwargs["SubnetId"] = subnet_id

    if key_name:
        run_kwargs["KeyName"] = key_name

    # Network interface for public IP control
    if subnet_id and assign_public_ip:
        run_kwargs.pop("SubnetId", None)
        run_kwargs["NetworkInterfaces"] = [
            {
                "DeviceIndex": 0,
                "SubnetId": subnet_id,
                "AssociatePublicIpAddress": assign_public_ip,
            }
        ]

    try:
        print("[AWS] Launching instance...")
        instances = ec2.create_instances(**run_kwargs)
        instance = instances[0]
        instance_id = instance.id
        print(f"[AWS] Instance launched: {instance_id}")

        # Wait for running state
        print("[AWS] Waiting for instance to reach 'running' state...")
        instance.wait_until_running()
        instance.reload()

        private_ip = instance.private_ip_address or "N/A"
        public_ip = instance.public_ip_address or "N/A"
        az = instance.placement.get("AvailabilityZone", "N/A")

        if install_agent and cmp.get("agent", {}).get("token"):
            print(f"[AWS] CMP Agent will auto-register within 2-3 minutes after boot")
            print(f"[AWS] View metrics on: Resource Detail → System Metrics tab")

        output = {
            "status": "success",
            "instance_id": instance_id,
            "instance_name": instance_name,
            "region": region,
            "availability_zone": az,
            "instance_type": instance_type,
            "private_ip": private_ip,
            "public_ip": public_ip,
            "instance_state": instance.state["Name"],
            "agent_installed": install_agent and bool(cmp.get("agent", {}).get("token")),
        }

        print(json.dumps(output))

    except ClientError as e:
        msg = e.response["Error"]["Message"]
        print(f"ERROR: AWS API error: {msg}")
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: Unexpected error: {e}")
        sys.exit(1)


main()
